channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - pip
  - notebook
  - pip:
    - azureml-defaults
    - azure-cognitiveservices-language-luis
    - numpy
    - pandas
    - scipy
    - matplotlib
    - seaborn
    - python-dotenv
    - joblib
    - tqdm
    - pydantic
    - ipywidgets
    - Markdown
    - jupyter_contrib_nbextensions
    - PyGithub