name: Function test and deploy

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FUNCTION_PATH: 'P10_04_function'
      FUNCTION_NAME: 'create_github_issue'
      PYTHON_VERSION: '3.8.8'
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: 'Create Function env file'
      env:
        FUNCTION_ENV: ${{ secrets.FUNCTION_ENV }}
      shell: bash
      run: |
        $CONDA/bin/python -c "import os; f = open('${{ env.FUNCTION_PATH }}/${{ env.FUNCTION_NAME }}/.env', 'w+'); f.write(os.getenv('FUNCTION_ENV')); f.close()"
    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.FUNCTION_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        popd
    - name: 'Test Azure function'
      shell: bash
      run: |
        pushd './${{ env.FUNCTION_PATH }}'
        python -m unittest -v
        popd
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      FUNCTION_PATH: 'P10_04_function'
      FUNCTION_NAME: 'create_github_issue'
      PYTHON_VERSION: '3.8.8'
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: 'Create Function env file'
      env:
        FUNCTION_ENV: ${{ secrets.FUNCTION_ENV }}
      shell: bash
      run: |
        $CONDA/bin/python -c "import os; f = open('${{ env.FUNCTION_PATH }}/${{ env.FUNCTION_NAME }}/.env', 'w+'); f.write(os.getenv('FUNCTION_ENV')); f.close()"
    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.FUNCTION_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        package: ${{ env.FUNCTION_PATH }}
        app-name: ${{ env.FUNCTION_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}
