name: LUIS deploy

on:
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_WORKSPACE: ${{ secrets.AZURE_WORKSPACE }}
  LUIS_PATH: 'P10_03_luis'
  PYTHON_VERSION: '3.8.8'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: 'Create LUIS env file'
      env:
        LUIS_ENV: ${{ secrets.LUIS_ENV }}
      shell: bash
      run: |
        $CONDA/bin/python -c "import os; f = open('${{ env.LUIS_PATH }}/.env', 'w+'); f.write(os.getenv('LUIS_ENV')); f.close()"
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: 'Update conda environment'
      shell: bash
      run: |
        $CONDA/bin/conda env update --file '${{ env.LUIS_PATH }}/conda_env.yml' --name base
    - name: 'Create, train, deploy on staging, test and delete model'
      shell: bash
      run: |
        pushd './${{ env.LUIS_PATH }}'
        $CONDA/bin/python train_deploy.py --is_staging 0 --is_tmp 0
        popd
