name: LUIS test

on:
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_WORKSPACE: ${{ secrets.AZURE_WORKSPACE }}
  LUIS_ENV: ${{ secrets.LUIS_ENV }}
  LUIS_PATH: 'P10_03_luis'
  PYTHON_VERSION: '3.8.8'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: 'Create LUIS env file'
      shell: bash
      run: |
        echo ${{ env.LUIS_ENV }} > '${{ env.LUIS_PATH }}/.env'
        tail '${{ env.LUIS_PATH }}/.env'
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: 'Update conda environment'
      shell: bash
      run: |
        $CONDA/bin/conda env update --file '${{ env.LUIS_PATH }}/conda_env.yml' --name base
    - name: 'Create, train, deploy, test and delete model'
      shell: bash
      run: |
        pushd './${{ env.LUIS_PATH }}'
        $CONDA/bin/python train_deploy.py --app_version 'tmp' --is_staging 1 --is_tmp 1
        popd
