name: Webapp deploy

on:
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  CHATBOT_PATH: '$GITHUB_WORKSPACE/P10_03_chatbot/'
  SCRIPT_NAME: 'chatbot_deploy.sh'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy on production'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          pushd './${{ env.CHATBOT_PATH }}'
          chmod +x ${{ env.SCRIPT_NAME }}
          ${{ env.SCRIPT_PATH }}
          popd
