name: Webapp test and deploy

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WEBAPP_PATH: 'P10_03_chatbot/webapp'
      PYTHON_VERSION: '3.8.8'
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: 'Create Webapp env file'
      env:
        WEBAPP_ENV: ${{ secrets.WEBAPP_ENV }}
      shell: bash
      run: |
        python -c "import os; f = open('${{ env.WEBAPP_PATH }}/.env', 'w+'); f.write(os.getenv('WEBAPP_ENV')); f.close()"
    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.WEBAPP_PATH }}'
        python -m pip install --upgrade pip
        pip install -r 'requirements.txt'
        popd
    - name: 'Test the webapp'
      shell: bash
      run: |
        pushd './${{ env.WEBAPP_PATH }}'
        python -m unittest -v
        popd
        
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      CHATBOT_PATH: $GITHUB_WORKSPACE/P10_03_chatbot
      SCRIPT_NAME: $GITHUB_WORKSPACE/P10_03_chatbot/chatbot_deploy.sh
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy on production'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          pushd ${{ env.CHATBOT_PATH }}
          chmod +x ${{ env.SCRIPT_NAME }}
          ${{ env.SCRIPT_NAME }}
          popd
